apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "common.name" . }}-db-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.dbSecret.userAssignedIdentityID }}
    keyvaultName: {{ .Values.dbSecret.keyvaultName }}
    objects: |
      array:
        - |
          objectName: {{ .Values.dbSecret.keyvaultSecretKey }}
          objectType: secret
    tenantId: {{ .Values.dbSecret.tenantId }}
  secretObjects:
    - secretName: {{ .Values.dbSecret.keyvaultName }}
      type: Opaque
      data:
        - objectName: {{ .Values.dbSecret.keyvaultSecretKey }}
          key: {{ .Values.dbSecret.keyvaultSecretKey }}