{{- if .Values.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mysql.name" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- with .Values.networkpolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector: 
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- toYaml .Values.networkpolicy.ingressFrom | nindent 8 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}