apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "mysql.name" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secret.userAssignedIdentityID }}
    keyvaultName: {{ .Values.secret.keyvaultName }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secret.keyvaultSecretKey }}
          objectType: secret
    tenantId: {{ .Values.secret.tenantId }}