{{- define "common.job" -}}
{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    spec:
      {{- with .Values.job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.job.securityContext | nindent 12 }}
          image: {{ .Values.job.image }}
          imagePullPolicy: {{ .Values.job.pullPolicy }}
          {{- with .Values.job.command }}
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.job.env | nindent 12 }}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
          {{- with .Values.job.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.job.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}
{{- end }}
{{- end }}